import type { GetServerSideProps, NextPage } from 'next';
import Router from 'next/router';
import Head from 'next/head';
import Image from 'next/image';

// assets
import homeIcon from '../public/assets/home-icon.png';
import starIcon from '../public/assets/star-icon.png';
import ratingIcon from '../public/assets/rating-icon.png';
import likeIcon from '../public/assets/like-icon.png';
import viewsIcon from '../public/assets/views-icon.png';
import dislikeIcon from '../public/assets/dislike-icon.png';

// components
import HeaderSidebar from '../src/components/HeaderSidebar';

// styles
import styles from '../styles/Home.module.scss';

type Movies = {
  id: string;
  title: string;
  year: number;
  rating: number;
  imageUrl: string;
};

interface IHomeProps {
  movies: Movies[];
}

const Home: NextPage<IHomeProps> = ({ movies }) => {
  const menus = [
    {
      icon: homeIcon,
      key: 'home',
      title: 'Home',
    },
    {
      icon: starIcon,
      key: 'favorite',
      title: 'Favorite',
    },
  ];

  const handleClickMovie = (movie: Movies) => {
    const { id } = movie || {};
    localStorage.setItem('movieData', JSON.stringify(movie));
    Router.push({
      pathname: `/${id}`,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderSidebar menus={menus}>
        <div className={styles.content}>
          {movies.length &&
            movies.map((movie, movieIndex) => (
              <div key={movieIndex} className={styles['movie-card']}>
                <div
                  className={styles['movie-card-container']}
                  style={{ backgroundImage: `url(${movie.imageUrl})` }}
                >
                  <div className={styles['movie-card-header']}>
                    <h4>{`${movie.title} (${movie.year})`}</h4>
                    <div className={styles['movie-card-rating']}>
                      <Image alt="" src={ratingIcon} width={16} height={16} />
                      <p>{`x${movie.rating}`}</p>
                    </div>
                  </div>
                  <div className={styles['movie-card-content']}>
                    <div className={styles['eye-icon']}>
                      <Image alt="" src={viewsIcon} width={24} height={24} />
                    </div>
                    <div className={styles['like-icon']}>
                      <Image alt="" src={likeIcon} width={24} height={24} />
                    </div>
                    <div className={styles['dislike-icon']}>
                      <Image alt="" src={dislikeIcon} width={24} height={24} />
                    </div>
                  </div>
                </div>
              </div>
            ))}
        </div>
      </HeaderSidebar>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<IHomeProps> = async () => {
  const data = await fetch(
    'https://private-2fff44-bncfetest.apiary-mock.com/movies',
    {
      method: 'GET',
    }
  )
    .then((response) => {
      if (response.status === 200) {
        console.log('Success fetch the data');
        return response.json();
      }
      console.log('Failed fetch the data');
    })
    .then((result) => result)
    .catch((err) => err);

  return {
    props: {
      movies: data.data,
    },
  };
};

export default Home;
